# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 13:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '校区信息'},
        ),
    ]
