# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0002_auto_20160523_1326'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': '课程信息', 'verbose_name_plural': '课程信息'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': '客户信息', 'verbose_name_plural': '客户信息'},
        ),
        migrations.AlterModelOptions(
            name='school',
            options={'verbose_name': '校区信息', 'verbose_name_plural': '校区信息'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': '讲师信息', 'verbose_name_plural': '讲师信息'},
        ),
    ]
