# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-23 13:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_auto_20160523_1329'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conultrecord',
            options={'verbose_name': '咨询记录', 'verbose_name_plural': '咨询记录'},
        ),
        migrations.AlterModelOptions(
            name='studyrecord',
            options={'verbose_name': '学习纪录', 'verbose_name_plural': '学习纪录'},
        ),
    ]
