# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-21 06:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('published', '已出版'), ('producing', '待出版'), ('forbidden', '销毁')], default='producing', max_length=32),
        ),
    ]
