# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 02:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='asset_system',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_info', models.CharField(max_length=50)),
                ('serv_info', models.CharField(max_length=50)),
                ('cpu_info', models.CharField(max_length=50)),
                ('disk_info', models.CharField(max_length=50)),
                ('mem_info', models.CharField(max_length=50)),
                ('load_info', models.CharField(max_length=50)),
                ('mark_info', models.CharField(blank=True, default='beijing_idc', max_length=50)),
            ],
        ),
    ]
