# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-10 05:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Galileo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='ip',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
